### ISSUE TITLE
Horrible effect on Edge / IE11

### ISSUE THREAD

**Issue by mihxew** [nk-o/jarallax#135] opened 2019-01-05 11:03 UTC
### Issue description:
So scrolling on Edge is really jerky and the image jumps slightly down and up while scrolling. This produces horrible effect that simply can't be used. (Note: Works fine in Chrome / Firefox /Brave /Vivaldi ....).

The same problem occurs on your https://free.nkdev.info/jarallax/

### Version used:
I am using the latest version. And the website was built with Mobirise. 
Microsoft EdgeHTML 17.17134

Are the devs aware of this issues? On IE11 is not really a problem but on Edge is...

**Comment by nk-o** [comment] 2019-01-06 13:36
Duplicate of https://github.com/nk-o/jarallax/issues/4, https://github.com/nk-o/jarallax/issues/25

If you have any info on how to fix this create replies in already created issues. Pull requests are also welcome.

**Closed by nk-o** 2019-01-06 13:36 UTC
