### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by dimizu** [nk-o/jarallax#129] opened 2018-10-23 16:47 UTC
### Issue description: I see in the console this error:

`'postMessage' konnte auf 'DOMWindow' nicht ausgeführt werden: Der angegebene Ziel-Ursprung (origin - 'https://www.youtube.com') stimmt nicht mit dem Empfängerfenster-Ursprung überein ('https://www.kellerhof.it').`

See live on this website: https://www.kellerhof.it

### Version used:
Jarallax  Version : 1.10.3
Video Background Extension for Jarallax Version : 1.0.1

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
<div class="parallax-window jarallax" data-jarallax='{"speed": 1, "videoVolume": 0, "videoPlayOnlyVisible": true}' data-jarallax-video="https://www.youtube-nocookie.com/embed/YGvUFPxxUhU" style="background-image: url(../images/videostandbild.jpg); min-height:600px;background-size: cover;">
<a href="hof.php#video"><i class="fas fa-caret-right"></i> Video mit Ton anschauen hier klicken!</a>
</div>
```

I also tried this video URL https://www.youtube.com/watch?v=YGvUFPxxUhU 
Same problem.

**Comment by nk-o** [comment] 2018-10-27 16:37
Duplicate of https://github.com/nk-o/jarallax/issues/120

**Closed by nk-o** 2018-10-27 16:37 UTC

**Comment by dimizu** [comment] 2018-10-28 08:04
@nk-o 
I don't understand why you mean that this is  a Duplicate of [https://github.com/nk-o/jarallax/issues/120](https://github.com/nk-o/jarallax/issues/120)? In my case also the origin and destination use https. I don't have a AD popup blocking extension, the error is shon in FF and also in Firefox always not from time to time an I can reproduce it always. The error is shon also in your demo: [https://free.nkdev.info/jarallax/](https://free.nkdev.info/jarallax/) always.

Since it apparently the problem is not the http vs https, perhaps has something to do with the order of loading. See this post about the same problem (different script) and the solution: [https://github.com/davidjbradshaw/iframe-resizer/issues/443#issuecomment-331721886](https://github.com/davidjbradshaw/iframe-resizer/issues/443#issuecomment-331721886)

Maybe that helps to find the issue...

**Comment by nk-o** [comment] 2018-10-28 09:05
@dimizu https and ad blocking are just assumptions. I still don't know what causes this error and how to fix it. Error in your case and in https://github.com/nk-o/jarallax/issues/120 the same, so I closed yours. Thank you for a possible solution.

**Comment by dimizu** [comment] 2018-10-28 17:56
> Error in your case and in #120 the same, so I closed yours

This is ok, no problem :-)  If I find out something else, I will answer under #120.
