### ISSUE TITLE
Disable Parallax on mobile is not working

### ISSUE THREAD

**Issue by nkanoi** [nk-o/jarallax#116] opened 2018-08-07 13:00 UTC
### Issue description:
jarallax(document.querySelectorAll('.jarallax'), {
    	disableParallax: /iPad|iPhone|iPod|Android/,
	    disableVideo: /iPad|iPhone|iPod|Android/
	});

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment] 2018-08-23 09:40
Working for me. Please, show me an online example with the bug.

**Comment by nk-o** [comment] 2018-08-23 10:33
Сlosed because this is a duplicate of https://github.com/nk-o/jarallax/issues/97

**Closed by nk-o** 2018-08-23 10:33 UTC
